install! 'cocoapods',
         :integrate_targets => false

use_frameworks!

platform :ios, '8.0'
target 'Apollo' do
	pod 'KSToastView'
end
Podfile
# Fix build error for mixed Bitcode frameworks in CocoaPods
post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['ENABLE_BITCODE'] = 'NO'
end
end
end